/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programasaludablegui3;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

/**
 *
 * @author villa_xaz9a7o
 */
public class ConsejosNutricionales {
    private static Map<String, List<String>> consejos = new HashMap<>();

    public ConsejosNutricionales() {
        cargarConsejos();
    }
    
    private static void cargarConsejos() {
        // Crea una lista de consejos para cada categoría de alimentos
        List<String> verdurasConsejos = new ArrayList<>();
        verdurasConsejos.add("Espinacas: Ricas en hierro, fibra y vitaminas.");
        verdurasConsejos.add("Brócoli: Fuente de vitamina C, fibra y compuestos antioxidantes.");
        verdurasConsejos.add("Zanahorias: Contienen betacarotenos que se convierten en vitamina A en el cuerpo.");
        verdurasConsejos.add("Pimientos: Excelente fuente de vitamina C y antioxidantes.");
        verdurasConsejos.add("Tomates: Ricos en licopeno, una sustancia antioxidante.");
        verdurasConsejos.add("Calabacines (zapallos): Bajos en calorías y versátiles en la cocina.");
        verdurasConsejos.add("Cebollas: Agregan sabor a numerosos platos y contienen antioxidantes.");
        verdurasConsejos.add("Berenjenas: Bajas en calorías y versátiles para asar, hornear o saltear.");
        verdurasConsejos.add("Col rizada (kale): Rica en vitamina K, vitamina C y calcio.");
        verdurasConsejos.add("Champiñones: Fuente de vitamina D y selenio.");
        verdurasConsejos.add("Puerros: Aportan sabor a sopas y guisos.");
        verdurasConsejos.add("Apio: Bajo en calorías y crujiente, ideal para bocadillos.");
        verdurasConsejos.add("Alcachofas: Contienen fibra y antioxidantes.");
        verdurasConsejos.add("Pepinos: Refrescantes y bajos en calorías.");
        verdurasConsejos.add("Patatas (papas): Una fuente de carbohidratos y vitamina C.");
        verdurasConsejos.add("Espárragos: Ricos en folato y vitamina K.");
        verdurasConsejos.add("Remolachas: Contienen antioxidantes y fibra.");
        verdurasConsejos.add("Chirivías: Similar a las zanahorias, pero con sabor ligeramente diferente.");
        verdurasConsejos.add("Rúcula: Hojas verdes con un sabor ligeramente picante.");
        verdurasConsejos.add("Coles de Bruselas: Contienen vitamina C y fibra.");
        verdurasConsejos.add("Nabos: Una raíz crucífera rica en nutrientes.");
        verdurasConsejos.add("Judías verdes (ejotes): Bajas en calorías y ricas en fibra.");
        verdurasConsejos.add("Lechuga iceberg: Refrescante y crujiente, ideal para ensaladas.");
        verdurasConsejos.add("Rábano: Un bocadillo crujiente y picante.");
        verdurasConsejos.add("Tomillo: Una hierba aromática que añade sabor a los platos.");
        verdurasConsejos.add("Perejil: Utilizado como condimento y fuente de vitamina K.");
        verdurasConsejos.add("Cilantro: Aporta sabor a muchas cocinas internacionales.");
        verdurasConsejos.add("Acelgas: Ricas en vitaminas y minerales.");
        verdurasConsejos.add("Hojas de mostaza: Hojas verdes con un sabor picante.");
        verdurasConsejos.add("Okra: Utilizada en platos del sur de Estados Unidos y otras cocinas.");
        verdurasConsejos.add("Chayote: Una verdura tropical versátil.");
        verdurasConsejos.add("Yuca: Una raíz almidonada utilizada en muchas culturas.");
        verdurasConsejos.add("Col china: Común en platos de cocina asiática.");
        verdurasConsejos.add("Rúcula: Hojas de sabor picante utilizadas en ensaladas y platos.");
        verdurasConsejos.add("Endivias: Se utilizan comúnmente en ensaladas y aperitivos.");
        verdurasConsejos.add("Espárragos de mar (samphire): Verdura marina crujiente.");
        verdurasConsejos.add("Algas marinas (nori, wakame, dulse): Utilizadas en cocina asiática y ricas en minerales.");
        verdurasConsejos.add("Chirivías (pastinacas): Raíz similar a la zanahoria pero con sabor ligeramente diferente.");
        verdurasConsejos.add("Ajo puerro: Utilizado en sopas y guisos.");
        verdurasConsejos.add("Achicoria: Hojas amargas utilizadas en ensaladas.");

        List<String> frutasConsejos = new ArrayList<>();
        frutasConsejos.add("Manzanas: Contienen fibra y antioxidantes.");
        frutasConsejos.add("Plátanos: Fuente de potasio y carbohidratos naturales.");
        frutasConsejos.add("Naranjas: Excelente fuente de vitamina C.");
        frutasConsejos.add("Uvas: Contienen antioxidantes y resveratrol.");
        frutasConsejos.add("Fresas: Bajas en calorías y ricas en vitamina C.");
        frutasConsejos.add("Kiwis: Ricos en vitamina C y fibra.");
        frutasConsejos.add("Mangos: Ricos en vitamina A y vitamina C.");
        frutasConsejos.add("Peras: Contienen fibra y antioxidantes.");
        frutasConsejos.add("Sandías: Refrescantes y bajas en calorías.");
        frutasConsejos.add("Melones: Fuente de vitamina C y vitamina A.");
        frutasConsejos.add("Cerezas: Contienen antioxidantes y vitamina C.");
        frutasConsejos.add("Duraznos: Ricos en vitamina C y fibra.");
        frutasConsejos.add("Limones: Fuente de vitamina C. Se pueden exprimir para hacer jugo o usar en aderezos.");
        frutasConsejos.add("Pomelos: Contienen vitamina C y antioxidantes. Pelar y comer en gajos o añadir a ensaladas.");
        frutasConsejos.add("Frambuesas: Bajas en calorías y ricas en fibra. Perfectas como bocadillo o en batidos.");
        frutasConsejos.add("Arándanos: Contienen antioxidantes y vitamina C. Disfrutar solos o añadir a yogur y cereales.");
        frutasConsejos.add("Papayas: Fuente de vitamina C y vitamina A. Cortar en trozos o añadir a ensaladas de frutas.");
        frutasConsejos.add("Guayabas: Contienen fibra y vitamina C. Comerlas crudas o hacer jugo.");
        frutasConsejos.add("Ciruelas: Ricas en fibra y antioxidantes. Perfectas como bocadillo o en compotas.");
        frutasConsejos.add("Higos: Contienen fibra y vitaminas. Comer frescos o secos.");
        frutasConsejos.add("Pera asiática (nashi): Refrescante y crujiente. Pelar y comer como bocadillo.");
        frutasConsejos.add("Granadas: Ricas en antioxidantes. Consumir los granos individuales o usar en ensaladas.");
        frutasConsejos.add("Cocos: Contienen grasas saludables y potasio. Consumir la carne y beber el agua de coco.");
        frutasConsejos.add("Piñas: Fuente de vitamina C y bromelina. Cortar y comer fresca o en jugos.");
        frutasConsejos.add("Litchis: Refrescantes y ricos en vitamina C. Pelar y comer como bocadillo.");
        frutasConsejos.add("Mandarinas: Fáciles de pelar y ricas en vitamina C. Disfrutar como bocadillo o en ensaladas.");
        frutasConsejos.add("Caquis: Ricos en vitamina A y vitamina C. Comer cuando estén maduros.");
        frutasConsejos.add("Grosellas: Contienen vitamina C y antioxidantes. Usar en mermeladas o como aderezo.");
        frutasConsejos.add("Maracuyá (fruta de la pasión): Rica en antioxidantes y vitamina C. Consumir la pulpa o usar en jugos.");
        frutasConsejos.add("Kiwano (melón africano): Exótico y refrescante. Cortar y comer la pulpa.");
        frutasConsejos.add("Chirimoya: Rica en fibra y vitamina C. Consumir la pulpa.");
        frutasConsejos.add("Guanábana: Contiene vitamina C y antioxidantes. Comer la pulpa o hacer jugo.");
        frutasConsejos.add("Carambola (fruta estrella): Con forma de estrella y rica en vitamina C. Cortar en rodajas y comer.");
        frutasConsejos.add("Mamey: Contiene fibra y vitamina A. Comer la pulpa.");
        frutasConsejos.add("Tamarindo: Utilizado en salsas y bebidas. Extraer la pulpa para usarla.");
        frutasConsejos.add("Pummelo: Similar al pomelo pero más grande. Pelar y comer en gajos.");
        frutasConsejos.add("Rambután: Exótico y con una cáscara peluda. Pelar y comer la pulpa.");

        List<String> granosConsejos = new ArrayList<>();
        granosConsejos.add("Arroz integral: Mayor contenido nutricional en comparación con el arroz blanco. Puede ser utilizado como base para platos o guarniciones.");
        granosConsejos.add("Quinua: Contiene proteínas completas y es rica en minerales como el hierro y el magnesio. Se puede usar como un sustituto de granos tradicionales en platos como ensaladas y guisos.");
        granosConsejos.add("Avena: Rica en fibra soluble que ayuda a mantener estable el azúcar en sangre. Ideal para el desayuno en forma de avena cocida o como ingrediente en batidos y galletas.");
        granosConsejos.add("Lentejas: Fuente de proteínas, fibra y hierro. Se utilizan en sopas, guisos o ensaladas.");
        granosConsejos.add("Garbanzos: Contienen proteínas, fibra y folato. Pueden ser utilizados en platos como hummus, guisos y ensaladas.");
        granosConsejos.add("Frijoles negros: Fuente de proteínas, fibra y antioxidantes. Comunes en la cocina mexicana y se usan en platos como los frijoles refritos.");
        granosConsejos.add("Couscous integral: Versátil y de cocción rápida. Se puede usar como base para ensaladas o como acompañamiento.");
        granosConsejos.add("Cebada: Rica en fibra y vitaminas B. Se utiliza en sopas y guisos.");
        granosConsejos.add("Mijo: Una buena fuente de carbohidratos y proteínas. Puede ser cocinado y servido como acompañamiento o en platos principales.");
        granosConsejos.add("Trigo sarraceno (buckwheat): Sin gluten y rico en antioxidantes. Puede ser utilizado en platos de desayuno, como gachas, o como guarnición.");
        granosConsejos.add("Cuscús de coliflor (cauliflower rice): Una alternativa baja en carbohidratos al cuscús tradicional. Puede ser utilizado en platos bajos en carbohidratos o como acompañamiento.");
        granosConsejos.add("Masa de harina de almendra: Sin gluten y rica en grasas saludables. Se utiliza en la preparación de productos horneados bajos en carbohidratos.");
        granosConsejos.add("Masa de harina de coco: Baja en carbohidratos y alta en fibra. Se utiliza en productos horneados sin gluten y bajos en carbohidratos.");
        granosConsejos.add("Cuscús de col rizada (kale couscous): Hecho con col rizada picada finamente y otros ingredientes. Una opción saludable y baja en carbohidratos en lugar del cuscús tradicional.");
        granosConsejos.add("Amaranto: Rico en proteínas y minerales. Puede ser cocido y utilizado en cereales calientes o añadido a batidos.");
        granosConsejos.add("Espelta (spelt): Un tipo de trigo antiguo con un perfil nutricional único. Se utiliza en productos horneados y cereales.");
        granosConsejos.add("Sorgo (sorghum): Sin gluten y rico en antioxidantes. Puede ser utilizado en ensaladas o como guarnición.");
        granosConsejos.add("Bulgur: Grano de trigo parcialmente cocido y triturado. Se usa comúnmente en ensaladas y platos mediterráneos.");
        granosConsejos.add("Centeno: Un grano utilizado en panes y cereales. Aporta un sabor distintivo a los productos horneados.");
        granosConsejos.add("Masa de harina de avena: Hecha a partir de avena molida. Se utiliza en productos horneados y cereales.");
        granosConsejos.add("Masa de harina de maíz (cornmeal): Hecha de maíz molido. Se utiliza en productos horneados y platos como la polenta.");
        granosConsejos.add("Freekeh: Grano de trigo verde tostado. Se utiliza en platos mediterráneos y ensaladas.");
        granosConsejos.add("Cebada de perla (pearl barley): Cebada que ha sido pulida para eliminar la cáscara. Se utiliza en sopas y guisos.");
        granosConsejos.add("Farro: Grano de trigo antiguo. Utilizado en ensaladas y platos italianos.");
        granosConsejos.add("Sémola de trigo: Hecha de trigo duro molido. Se utiliza en productos horneados y platos como la sémola.");
        granosConsejos.add("Teff: Un grano sin gluten nativo de Etiopía. Utilizado en pan sin gluten y platos tradicionales etíopes.");
        granosConsejos.add("Masa de harina de arroz: Hecha de arroz molido. Utilizada en productos horneados sin gluten y cocina asiática.");
        granosConsejos.add("Sémola de maíz (polenta): Harina de maíz cocida. Se utiliza en platos como la polenta o se deja enfriar y luego se corta en trozos.");
        granosConsejos.add("Cuscús de calabaza (pumpkin couscous): Hecho con calabaza triturada. Utilizado en platos bajos en carbohidratos o como acompañamiento.");
        granosConsejos.add("Sémola de maíz de grano entero (whole grain cornmeal): Hecha de maíz de grano entero molido. Utilizada en productos horneados y platos como la polenta.");
        granosConsejos.add("Couscous de coliflor (cauliflower couscous): Hecho con coliflor triturada. Baja en carbohidratos y utilizada como sustituto del cuscús.");
        granosConsejos.add("Cuscús de zanahoria (carrot couscous): Hecho con zanahorias ralladas. Utilizado como una alternativa baja en carbohidratos al cuscús tradicional.");
        granosConsejos.add("Fregola Sarda: Una variedad de sémola de trigo tostada. Utilizada en platos de la cocina italiana de Cerdeña.");
        granosConsejos.add("Cuscús de camote (sweet potato couscous): Hecho con camote (batata) rallado. Utilizado en platos bajos en carbohidratos o como acompañamiento.");
        granosConsejos.add("Masa de harina de almendra blanqueada: Harina de almendra sin piel. Utilizada en productos horneados bajos en carbohidratos.");
        granosConsejos.add("Harina de coco blanqueada: Harina de coco sin piel. Utilizada en productos horneados sin gluten y bajos en carbohidratos.");

        List<String> legumbresConsejos = new ArrayList<>();
        legumbresConsejos.add("Lentejas: Fuente de proteínas, fibra y hierro. Se utilizan en sopas, guisos o ensaladas.");
        legumbresConsejos.add("Garbanzos: Contienen proteínas, fibra y folato. Pueden ser utilizados en platos como hummus, guisos y ensaladas.");
        legumbresConsejos.add("Frijoles negros: Fuente de proteínas, fibra y antioxidantes. Comunes en la cocina mexicana y se usan en platos como los frijoles refritos.");
        legumbresConsejos.add("Frijoles pintos: Ricos en proteínas y fibra. Se utilizan en platos como los frijoles refritos o chili.");
        legumbresConsejos.add("Frijoles blancos (cannellini): Contienen proteínas y fibra. Se usan en platos como sopas y ensaladas.");
        legumbresConsejos.add("Frijoles rojos: Fuente de proteínas y fibra. Comunes en platos como el arroz y frijoles.");
        legumbresConsejos.add("Guisantes (chícharos): Contienen proteínas y fibra. Se utilizan en guisos, sopas y como acompañamiento.");
        legumbresConsejos.add("Habas (fava beans): Fuente de proteínas y fibra. Se utilizan en platos mediterráneos y ensaladas.");
        legumbresConsejos.add("Alubias (black-eyed peas): Contienen proteínas y fibra. Comunes en la cocina sureña de Estados Unidos.");
        legumbresConsejos.add("Soja (soybeans): Ricas en proteínas y utilizadas en productos como el tofu y la leche de soja.");
        legumbresConsejos.add("Cacahuetes (maníes): Fuente de proteínas y grasas saludables. Se consumen como bocadillo o se utilizan para hacer mantequilla de maní.");
        legumbresConsejos.add("Judías verdes (green beans): Bajas en calorías y fuente de fibra. Se utilizan en platos salteados o al vapor.");
        legumbresConsejos.add("Hummus: Hecho principalmente con garbanzos. Se utiliza como dip o untado en pan pita.");
        legumbresConsejos.add("Edamame: Soja inmadura cocida en vainas. Se sirve como aperitivo o en ensaladas.");
        legumbresConsejos.add("Frijoles mungo (mung beans): Fuente de proteínas y utilizados en platos asiáticos como los fideos de soja.");
        legumbresConsejos.add("Frijoles adzuki: Pequeños frijoles rojos utilizados en la cocina asiática y postres.");
        legumbresConsejos.add("Frijoles negros fermentados (natto): Comunes en la cocina japonesa. Se utilizan como acompañamiento.");
        legumbresConsejos.add("Tofu: Hecho de soja coagulada. Se utiliza en platos veganos y vegetarianos.");
        legumbresConsejos.add("Tempeh: Bloques fermentados de soja. Se utilizan en platos veganos y vegetarianos.");
        legumbresConsejos.add("Lupini: Legumbre de gran tamaño utilizada como aperitivo en algunos países mediterráneos.");
        legumbresConsejos.add("Frijoles carioca: Variedad de frijoles comunes en América Latina. Se utilizan en platos como la feijoada brasileña.");
        legumbresConsejos.add("Frijoles ayocote: Variedad de frijoles de América Latina. Utilizados en diferentes platos regionales.");
        legumbresConsejos.add("Frijoles peruanos (pallares): Variedad de frijoles comunes en la cocina peruana. Se utilizan en platos como el 'tacu tacu.'");
        legumbresConsejos.add("Frijoles azuki: Pequeños frijoles rojos utilizados en la cocina asiática y postres.");
        legumbresConsejos.add("Frijoles canarios (canary beans): Variedad de frijoles de América Latina. Se utilizan en platos como el 'casamiento' en El Salvador.");
        legumbresConsejos.add("Frijoles rojos del norte: Variedad de frijoles comunes en la cocina mexicana. Se utilizan en platos como los 'frijoles charros.'");
        legumbresConsejos.add("Frijoles tarbais: Variedad de frijoles utilizados en la cocina francesa, especialmente en el cassoulet.");
        legumbresConsejos.add("Frijoles negros de ojo (black-eyed beans): Variedad de frijoles comunes en la cocina africana y del sur de Estados Unidos.");
        legumbresConsejos.add("Frijoles borlotti: Variedad de frijoles utilizados en la cocina italiana. Se utilizan en platos como la minestrone.");
        legumbresConsejos.add("Frijoles lima (butter beans): Variedad de frijoles grandes utilizados en platos como el succotash en Estados Unidos.");
        legumbresConsejos.add("Frijoles rojos azucarados (cranberry beans): Variedad de frijoles utilizados en la cocina italiana y en algunos platos mediterráneos.");
        legumbresConsejos.add("Frijoles tepary: Variedad de frijoles nativos de América del Norte y utilizados por comunidades indígenas.");
        legumbresConsejos.add("Frijoles de Lima gigantes: Variedad de frijoles grandes utilizados en la cocina italiana.");
        legumbresConsejos.add("Frijoles Jacob's Cattle: Variedad de frijoles con un patrón distintivo en blanco y negro.");
        legumbresConsejos.add("Frijoles Anasazi: Variedad de frijoles nativa de América del Norte y utilizada por tribus indígenas.");

        List<String> proteinasConsejos = new ArrayList<>();
        proteinasConsejos.add("Pechuga de pollo sin piel: Alta en proteínas y baja en grasas. Se puede asar, hornear o a la parrilla.");
        proteinasConsejos.add("Pavo: Otra fuente magra de proteínas. Ideal para sándwiches, ensaladas o platos principales.");
        proteinasConsejos.add("Pescado (salmón, trucha, sardinas): Rico en ácidos grasos omega-3 beneficiosos para el corazón. Se puede cocinar al horno, a la parrilla o enlatado.");
        proteinasConsejos.add("Tilapia: Pescado blanco magro con bajo contenido de grasa. Se puede cocinar de diversas formas, como a la parrilla o al horno.");
        proteinasConsejos.add("Pechuga de pavo molida: Baja en grasa y alta en proteínas. Se utiliza en platos como hamburguesas de pavo y albóndigas.");
        proteinasConsejos.add("Clara de huevo: Fuente pura de proteína sin grasa. Se puede cocinar de muchas formas, como huevos revueltos o claras cocidas.");
        proteinasConsejos.add("Filete de pescado blanco (por ejemplo, lenguado): Bajo en grasa y alto en proteínas. Se puede cocinar a la parrilla o al horno.");
        proteinasConsejos.add("Pechuga de pato sin piel: Contiene menos grasa que otras partes del pato. Se cocina de diversas formas, como asado o a la parrilla.");
        proteinasConsejos.add("Pavo molido: Otra opción magra de proteína de pavo. Utilizado en platos como lasañas y tacos.");
        proteinasConsejos.add("Pollo de corral: Contiene menos grasa que el pollo de granja industrial. Se cocina de diversas formas, como asado o a la parrilla.");
        proteinasConsejos.add("Conejo: Carne magra y sabrosa. Se cocina en estofados o a la parrilla.");
        proteinasConsejos.add("Carne de res magra (como el lomo): Cortes magros de carne de res. Se cocina a la parrilla o al horno.");
        proteinasConsejos.add("Carne de cerdo magra (como el solomillo de cerdo): Cortes magros de carne de cerdo. Se cocina a la parrilla o al horno.");
        proteinasConsejos.add("Pavo ahumado bajo en sodio: Fuente magra de proteínas con bajo contenido de sodio. Se utiliza en sándwiches y ensaladas.");
        proteinasConsejos.add("Carne de cordero magra (como el filete de pierna): Cortes magros de carne de cordero. Se cocinan a la parrilla o en guisos.");
        proteinasConsejos.add("Carne de búfalo (buffalo): Baja en grasa y alta en proteínas. Se utiliza en hamburguesas de búfalo y chili.");
        proteinasConsejos.add("Pechuga de pollo orgánico: Pollo criado orgánicamente con menos grasa. Se puede cocinar de diversas formas.");
        proteinasConsejos.add("Pechuga de pavo orgánico: Pavo criado orgánicamente con menos grasa. Se utiliza en platos como sándwiches y ensaladas.");
        proteinasConsejos.add("Camarones: Bajos en grasa y ricos en proteínas. Se pueden cocinar a la parrilla, salteados o en sopas.");
        proteinasConsejos.add("Pechuga de pollo desmenuzada (shredded chicken): Pechuga de pollo cocida y desmenuzada. Utilizada en tacos, ensaladas y wraps.");
        proteinasConsejos.add("Filete de pescado de agua fría (como el bacalao): Bajo en grasa y alto en proteínas. Se puede cocinar al horno o a la parrilla.");
        proteinasConsejos.add("Anchoas: Peces pequeños ricos en proteínas y grasas saludables. Se utilizan en ensaladas, pizzas y salsas.");
        proteinasConsejos.add("Pechuga de pollo a la parrilla en rodajas: Pechuga de pollo a la parrilla cortada en rodajas. Utilizada en ensaladas y wraps.");
        proteinasConsejos.add("Salmón enlatado: Rico en proteínas y ácidos grasos omega-3. Se utiliza en ensaladas y sándwiches.");
        proteinasConsejos.add("Ternera magra molida (como el 93% de carne magra): Carne de res molida con bajo contenido de grasa. Se utiliza en hamburguesas y tacos.");
        proteinasConsejos.add("Carne de cerdo molida magra: Carne de cerdo molida con bajo contenido de grasa. Se utiliza en platos como albóndigas y tacos.");
        proteinasConsejos.add("Pollo a la parrilla desmenuzado (shredded grilled chicken): Pechuga de pollo a la parrilla desmenuzada. Utilizada en ensaladas y wraps.");
        proteinasConsejos.add("Cordero deshuesado y magro (boneless leg of lamb): Carne de cordero deshuesada y magra. Se cocina a la parrilla o en guisos.");
        proteinasConsejos.add("Carne de búfalo molida (buffalo ground meat): Carne de búfalo molida baja en grasa. Utilizada en hamburguesas y chili.");
        proteinasConsejos.add("Pollo deshuesado y magro (boneless skinless chicken): Pechuga de pollo deshuesada y magra. Se puede cocinar de diversas formas.");
        proteinasConsejos.add("Pavo deshuesado y magro (boneless skinless turkey): Pavo deshuesado y magro. Se utiliza en platos como chile de pavo.");
        proteinasConsejos.add("Filete de pescado blanco a la parrilla (grilled white fish): Bajo en grasa y alto en proteínas. Se puede cocinar a la parrilla o al horno.");
        proteinasConsejos.add("Salmón fresco: Rico en ácidos grasos omega-3. Se cocina al horno, a la parrilla o a la plancha.");
        proteinasConsejos.add("Carne de res magra en tiras (beef strips): Tiras de carne de res magra. Se utilizan en platos como stir-fry (salteados).");
        proteinasConsejos.add("Carne de cerdo magra en tiras (pork strips): Tiras de carne de cerdo magra. Se utilizan en platos como stir-fry (salteados).");
        proteinasConsejos.add("Pollo deshuesado y magro en tiras (boneless skinless chicken strips): Tiras de pechuga de pollo deshuesada y magra. Se utilizan en platos como stir-fry (salteados).");
        proteinasConsejos.add("Pechuga de pavo en rodajas finas (thin-sliced turkey breast): Pechuga de pavo en rodajas finas. Utilizada en sándwiches y envolturas.");
        proteinasConsejos.add("Camarones cocidos: Bajos en grasa y ricos en proteínas. Se pueden añadir a ensaladas, pastas o servir como aperitivo.");
        proteinasConsejos.add("Carne de res magra en cubos (beef cubes): Cubos de carne de res magra. Se utilizan en guisos y estofados.");
        proteinasConsejos.add("Carne de cerdo magra en cubos (pork cubes): Cubos de carne de cerdo magra. Se utilizan en guisos y estofados.");
        proteinasConsejos.add("Pollo deshuesado y magro en cubos (boneless skinless chicken cubes): Cubos de pechuga de pollo deshuesada y magra. Se utilizan en guisos y estofados.");

        List<String> grasasConsejos = new ArrayList<>();
        grasasConsejos.add("Aguacate: Rico en grasas monoinsaturadas y potasio. Se utiliza en ensaladas, guacamole y como acompañamiento.");
        grasasConsejos.add("Nueces: Contienen grasas saludables y antioxidantes. Se pueden consumir como bocadillo o agregar a ensaladas.");
        grasasConsejos.add("Aceite de oliva virgen extra: Buena fuente de grasas monoinsaturadas. Utilizado para cocinar y como aderezo para ensaladas.");
        grasasConsejos.add("Aceitunas: Contienen grasas saludables y antioxidantes. Se consumen como aperitivo o se utilizan en ensaladas y platos mediterráneos.");
        grasasConsejos.add("Aceite de aguacate: Proveniente del aguacate y rico en grasas saludables. Se utiliza para cocinar y como aderezo.");
        grasasConsejos.add("Aceite de nuez: Hecho de nueces y rico en grasas saludables. Se utiliza en aderezos y salsas.");
        grasasConsejos.add("Aceite de coco virgen: Contiene grasas saturadas saludables. Se utiliza para cocinar y en productos horneados.");
        grasasConsejos.add("Aceite de cáñamo: Proveniente de semillas de cáñamo y rico en grasas saludables. Utilizado en aderezos y salsas.");
        grasasConsejos.add("Aceite de linaza (flaxseed oil): Hecho de semillas de linaza y rico en grasas saludables. Se utiliza en aderezos y batidos.");
        grasasConsejos.add("Aceite de sésamo (sesame oil): Proveniente de semillas de sésamo y rico en grasas saludables. Utilizado en platos asiáticos y aderezos.");
        grasasConsejos.add("Aceite de macadamia: Hecho de nueces de macadamia y rico en grasas saludables. Utilizado en aderezos y salsas.");
        grasasConsejos.add("Aceite de pistacho: Proveniente de nueces de pistacho y rico en grasas saludables. Utilizado en aderezos y platos mediterráneos.");
        grasasConsejos.add("Aceite de almendra: Hecho de almendras y rico en grasas saludables. Utilizado en aderezos y productos horneados.");
        grasasConsejos.add("Aceite de avellana (hazelnut oil): Proveniente de avellanas y rico en grasas saludables. Utilizado en aderezos y salsas.");
        grasasConsejos.add("Aceite de germen de trigo (wheat germ oil): Hecho del germen de trigo y rico en grasas saludables. Utilizado en aderezos y batidos.");
        grasasConsejos.add("Aceite de semilla de uva (grape seed oil): Proveniente de semillas de uva y rico en grasas saludables. Utilizado en aderezos y cocina de alta temperatura.");
        grasasConsejos.add("Aceite de cártamo (safflower oil): Hecho de semillas de cártamo y rico en grasas saludables. Utilizado para cocinar y en aderezos.");
        grasasConsejos.add("Aceite de canola: Rico en grasas monoinsaturadas y bajo en grasas saturadas. Se utiliza en cocina y horneado.");
        grasasConsejos.add("Aceite de cáñamo: Hecho de semillas de cáñamo y rico en grasas saludables. Utilizado en aderezos y salsas.");
        grasasConsejos.add("Aceite de chía (chia seed oil): Proveniente de semillas de chía y rico en grasas saludables. Se utiliza en aderezos y batidos.");
        grasasConsejos.add("Aceite de pescado (fish oil): Rico en ácidos grasos omega-3 beneficiosos para la salud cardiovascular. Disponible en cápsulas o líquido como suplemento.");
        grasasConsejos.add("Aceite de linaza (flaxseed oil): Hecho de semillas de linaza y rico en ácidos grasos omega-3. Se utiliza en aderezos y batidos.");
        grasasConsejos.add("Aceite de krill: Proveniente del krill y rico en ácidos grasos omega-3. Disponible en cápsulas como suplemento.");
        grasasConsejos.add("Mantequilla de almendras (almond butter): Hecha de almendras y rica en grasas saludables. Se utiliza en bocadillos y batidos.");
        grasasConsejos.add("Mantequilla de cacahuete (peanut butter): Hecha de cacahuetes y rica en grasas saludables. Se utiliza en bocadillos y sándwiches.");
        grasasConsejos.add("Mantequilla de nuez (nut butter): Hecha de diversas nueces y rica en grasas saludables. Se utiliza en bocadillos y batidos.");
        grasasConsejos.add("Semillas de chía (chia seeds): Contienen grasas saludables y fibra. Se pueden agregar a batidos, yogur y cereales.");
        grasasConsejos.add("Semillas de lino (flaxseeds): Ricas en grasas saludables y fibra. Se pueden agregar a batidos, yogur y productos horneados.");
        grasasConsejos.add("Semillas de cáñamo (hemp seeds): Contienen grasas saludables y proteínas. Se pueden agregar a batidos, ensaladas y yogur.");
        grasasConsejos.add("Semillas de girasol (sunflower seeds): Contienen grasas saludables y vitamina E. Se pueden consumir como aperitivo o agregar a ensaladas.");
        grasasConsejos.add("Semillas de calabaza (pumpkin seeds): Contienen grasas saludables y son ricas en minerales. Se pueden consumir como aperitivo o agregar a ensaladas.");
        grasasConsejos.add("Aguacate en rodajas: Rodajas de aguacate fresco. Se utilizan en ensaladas, sándwiches y tacos.");
        grasasConsejos.add("Aguacate en puré: Aguacate machacado en forma de puré. Se utiliza como aderezo o para hacer guacamole.");

        List<String> lacteosConsejos = new ArrayList<>();
        lacteosConsejos.add("Yogur griego sin grasa: Alto en proteínas y bajo en grasa. Se puede consumir solo o con frutas y miel.");
        lacteosConsejos.add("Leche desnatada o baja en grasa: Fuente de calcio y vitamina D. Se utiliza en cereales, batidos y como base para salsas.");
        lacteosConsejos.add("Queso cottage bajo en grasa: Alto en proteínas y bajo en grasa. Se puede consumir con frutas o como relleno de ensaladas.");
        lacteosConsejos.add("Queso ricotta bajo en grasa: Bajo en grasa y rico en proteínas. Se utiliza en platos como lasañas y rellenos de pasta.");
        lacteosConsejos.add("Queso feta bajo en grasa: Bajo en grasa y utilizado en ensaladas y platos mediterráneos.");
        lacteosConsejos.add("Queso suizo bajo en grasa: Bajo en grasa y utilizado en sándwiches y platos fundidos.");
        lacteosConsejos.add("Leche de almendra sin azúcar añadido: Baja en calorías y grasa. Se utiliza en batidos, cereales y café.");
        lacteosConsejos.add("Leche de soja sin azúcar añadido: Fuente de proteínas y baja en grasa. Se utiliza en batidos, cereales y café.");
        lacteosConsejos.add("Yogur de soja sin azúcar añadido: Alternativa sin lácteos, rica en proteínas y baja en grasa. Se consume solo o con frutas.");
        lacteosConsejos.add("Queso cheddar bajo en grasa: Bajo en grasa y utilizado en sándwiches y platos fundidos.");
        lacteosConsejos.add("Yogur de coco sin azúcar añadido: Alternativa al lácteo con sabor a coco y bajo en grasa. Se consume solo o con frutas.");
        lacteosConsejos.add("Queso mozzarella bajo en grasa: Bajo en grasa y utilizado en pizzas y platos fundidos.");
        lacteosConsejos.add("Leche de avena sin azúcar añadido: Alternativa sin lácteos, baja en grasa y sin azúcar añadido. Se utiliza en batidos, cereales y café.");
        lacteosConsejos.add("Yogur de almendra sin azúcar añadido: Alternativa al lácteo con sabor a almendra y bajo en grasa. Se consume solo o con frutas.");
        lacteosConsejos.add("Queso cottage bajo en grasa con hierbas: Alto en proteínas, bajo en grasa y aromatizado con hierbas. Se consume con frutas o como relleno de ensaladas.");
        lacteosConsejos.add("Yogur de coco con frutas sin azúcar añadido: Alternativa al lácteo con sabor a coco y frutas, bajo en grasa. Se consume solo o con más frutas.");
        lacteosConsejos.add("Leche de almendra con vainilla sin azúcar añadido: Alternativa sin lácteos, baja en grasa, con sabor a vainilla y sin azúcar añadido. Se utiliza en batidos, cereales y café.");
        lacteosConsejos.add("Yogur de almendra con vainilla y canela sin azúcar añadido: Alternativa al lácteo con sabor a vainilla y canela, bajo en grasa y sin azúcar añadido. Se consume solo o con frutas.");
        lacteosConsejos.add("Yogur de coco con probióticos: Alternativa al lácteo, rico en proteínas y probióticos, bajo en grasa. Se consume solo o con frutas.");
        lacteosConsejos.add("Leche de coco sin azúcar añadido: Alternativa sin lácteos, baja en grasa y sin azúcar añadido. Se utiliza en batidos, cereales y café.");
        lacteosConsejos.add("Queso crema bajo en grasa: Bajo en grasa y utilizado en bagels y como aderezo.");
        lacteosConsejos.add("Yogur de avena con frutas sin azúcar añadido: Alternativa sin lácteos con sabor a avena y frutas, bajo en grasa y sin azúcar añadido. Se consume solo o con más frutas.");
        lacteosConsejos.add("Leche de almendra con canela sin azúcar añadido: Alternativa sin lácteos, baja en grasa, con sabor a canela y sin azúcar añadido. Se utiliza en batidos, cereales y café.");

        List<String> especiasConsejos = new ArrayList<>();
        especiasConsejos.add("Cúrcuma: Tiene propiedades antiinflamatorias. Se utiliza en curries, sopas y guisos.");
        especiasConsejos.add("Ajo: Puede tener beneficios para la salud cardiovascular. Se utiliza en salsas, adobos y platos salteados.");
        especiasConsejos.add("Albahaca: Contiene antioxidantes y puede tener propiedades antiinflamatorias. Se utiliza en pesto, ensaladas y platos italianos.");
        especiasConsejos.add("Pimienta negra: Agrega sabor y a menudo se combina con otras especias. Se utiliza en una amplia variedad de platos.");
        especiasConsejos.add("Canela: Puede ayudar a regular el azúcar en sangre. Se utiliza en postres, batidos y bebidas calientes.");
        especiasConsejos.add("Jengibre: Tiene propiedades antiinflamatorias y puede ayudar a aliviar las náuseas. Se utiliza en platos asiáticos, tés y batidos.");
        especiasConsejos.add("Orégano: Rico en antioxidantes y sabor. Se utiliza en pizzas, pastas y platos mediterráneos.");
        especiasConsejos.add("Comino: Aporta un sabor terroso y especiado. Se utiliza en platos de Medio Oriente, mexicanos e indios.");
        especiasConsejos.add("Cilantro: Agrega frescura y se utiliza en muchas cocinas del mundo. Se utiliza en ensaladas, salsas y platos de Medio Oriente y mexicanos.");
        especiasConsejos.add("Romero: Tiene un aroma robusto y se utiliza en platos asados y carnes. Se utiliza en asados, guisos y panes.");
        especiasConsejos.add("Pimentón: Aporta sabor y color. Se utiliza en adobos, sopas y guisos.");
        especiasConsejos.add("Tomillo: Tiene un sabor terroso y se utiliza en platos europeos. Se utiliza en asados, guisos y platos mediterráneos.");
        especiasConsejos.add("Salvia: Agrega un sabor herbáceo y se utiliza en platos de Acción de Gracias. Se utiliza en relleno de pavo, platos de cerdo y pasta.");
        especiasConsejos.add("Menta: Agrega frescura y se utiliza en postres y bebidas. Se utiliza en postres, cócteles y tés.");
        especiasConsejos.add("Perejil: Aporta frescura y se utiliza en muchas cocinas. Se utiliza en ensaladas, salsas y platos mediterráneos.");
        especiasConsejos.add("Nuez moscada: Agrega sabor y a menudo se usa en platos cremosos. Se utiliza en salsas, purés y postres.");
        especiasConsejos.add("Estragón: Tiene un sabor distintivo y se utiliza en salsas. Se utiliza en salsas de mostaza y platos de pollo.");
        especiasConsejos.add("Hinojo: Aporta un sabor anisado y se utiliza en platos mediterráneos. Se utiliza en ensaladas, sopas y asados.");
        especiasConsejos.add("Pimienta de cayena: Agrega picante y se utiliza en platos picantes. Se utiliza en salsas, adobos y comidas picantes.");
        especiasConsejos.add("Clavo de olor: Tiene un sabor fuerte y se utiliza en postres y salsas. Se utiliza en postres, salsas y bebidas calientes.");
        especiasConsejos.add("Cardamomo: Aporta un sabor dulce y se utiliza en platos de Medio Oriente e India. Se utiliza en curries, postres y tés.");
        especiasConsejos.add("Hojas de laurel: Aporta aroma y se utiliza en sopas y guisos. Se utiliza en sopas, guisos y salsas.");
        especiasConsejos.add("Eneldo: Agrega un sabor fresco y se utiliza en platos de pescado y pepinillos. Se utiliza en platos de pescado, ensaladas y pepinillos.");
        especiasConsejos.add("Pimienta de Jamaica (allspice): Aporta un sabor cálido y especiado. Se utiliza en postres, salsas y platos caribeños.");
        especiasConsejos.add("Azafrán: Aporta color y sabor a platos especiales. Se utiliza en paella, risotto y platos mediterráneos.");
        especiasConsejos.add("Estragón: Tiene un sabor distintivo y se utiliza en salsas. Se utiliza en salsas de mostaza y platos de pollo.");
        especiasConsejos.add("Hierbabuena: Agrega frescura y se utiliza en postres y bebidas. Se utiliza en postres, cócteles y tés.");
        especiasConsejos.add("Hojas de laurel: Aporta aroma y se utiliza en sopas y guisos. Se utiliza en sopas, guisos y salsas.");
        especiasConsejos.add("Eneldo: Agrega un sabor fresco y se utiliza en platos de pescado y pepinillos. Se utiliza en platos de pescado, ensaladas y pepinillos.");
        especiasConsejos.add("Pimienta de Jamaica (allspice): Aporta un sabor cálido y especiado. Se utiliza en postres, salsas y platos caribeños.");
        especiasConsejos.add("Azafrán: Aporta color y sabor a platos especiales. Se utiliza en paella, risotto y platos mediterráneos.");

        List<String> bebidasConsejos = new ArrayList<>();
        bebidasConsejos.add("Agua: Es esencial para la hidratación y el funcionamiento adecuado del cuerpo.");
        bebidasConsejos.add("Té verde: Rico en antioxidantes y puede tener beneficios para la salud.");
        bebidasConsejos.add("Té negro: Contiene antioxidantes y un sabor más fuerte que el té verde.");
        bebidasConsejos.add("Té de hierbas: Varias variedades, como manzanilla y menta, con propiedades calmantes.");
        bebidasConsejos.add("Té de jengibre: Puede ayudar a aliviar las náuseas y tener propiedades antiinflamatorias.");
        bebidasConsejos.add("Infusión de frutas: Agua infusionada con frutas como limón, naranja o fresas para un sabor natural.");
        bebidasConsejos.add("Agua con gas natural: Una alternativa refrescante al agua plana.");
        bebidasConsejos.add("Leche de almendra sin azúcar añadido: Alternativa sin lácteos, baja en calorías y grasa.");
        bebidasConsejos.add("Leche de soja sin azúcar añadido: Fuente de proteínas y baja en grasa, adecuada para personas con intolerancia a la lactosa.");
        bebidasConsejos.add("Jugo de naranja recién exprimido: Rico en vitamina C y antioxidantes cuando se consume con moderación.");
        bebidasConsejos.add("Jugo de manzana sin azúcar añadido: Fuente de vitamina C y antioxidantes, pero controla el consumo debido al azúcar natural.");
        bebidasConsejos.add("Batido de proteínas: Hecho con proteína en polvo, leche o agua, y frutas para aumentar el contenido nutricional.");
        bebidasConsejos.add("Batido verde: Mezcla de hojas verdes, como espinacas o kale, con frutas y líquidos.");
        bebidasConsejos.add("Leche de coco sin azúcar añadido: Alternativa sin lácteos, con un sabor a coco distintivo.");
        bebidasConsejos.add("Batido de proteínas vegetales: Hecho con proteínas de plantas como soja o guisantes.");
        bebidasConsejos.add("Café negro: Bajo en calorías y puede tener beneficios para la concentración.");
        bebidasConsejos.add("Café con leche baja en grasa: Café mezclado con leche baja en grasa para reducir las calorías.");
        bebidasConsejos.add("Batido de bayas: Hecho con bayas como fresas y arándanos, ricas en antioxidantes.");
        bebidasConsejos.add("Agua de coco: Una fuente natural de electrolitos y bajo en calorías.");
        bebidasConsejos.add("Kombucha: Bebida fermentada con posibles beneficios para la salud intestinal.");
        bebidasConsejos.add("Leche de almendra con vainilla sin azúcar añadido: Alternativa sin lácteos, baja en calorías y con sabor a vainilla.");
        bebidasConsejos.add("Leche de soja con vainilla sin azúcar añadido: Fuente de proteínas, con sabor a vainilla y sin azúcar añadido.");
        bebidasConsejos.add("Batido de proteínas de suero de leche: Hecho con proteína de suero de leche en polvo, leche o agua.");
        bebidasConsejos.add("Agua mineral con gas: Refrescante y con burbujas naturales.");
        bebidasConsejos.add("Té de menta: Puede ayudar a la digestión y tiene un sabor refrescante.");
        bebidasConsejos.add("Leche de almendra con chocolate sin azúcar añadido: Alternativa sin lácteos, baja en calorías y con sabor a chocolate.");
        bebidasConsejos.add("Agua con infusión de pepino y limón: Refrescante y con un sabor suave.");
        bebidasConsejos.add("Café descafeinado: Una opción baja en cafeína para quienes desean reducir su consumo de cafeína.");
        bebidasConsejos.add("Té de cúrcuma: Puede tener propiedades antiinflamatorias y antioxidantes.");
        bebidasConsejos.add("Infusión de hibisco: Puede ayudar a mantener la presión arterial y es refrescante.");
        bebidasConsejos.add("Leche de avena sin azúcar añadido: Alternativa sin lácteos, baja en calorías y con sabor a avena.");
        bebidasConsejos.add("Té de canela: Puede ayudar a regular el azúcar en sangre y tiene un sabor cálido.");

        List<String> snacksConsejos = new ArrayList<>();
        snacksConsejos.add("Palitos de zanahoria con hummus: Combinación de verduras y proteínas. Un aperitivo saludable y satisfactorio.");
        snacksConsejos.add("Frutas frescas: Una opción natural y dulce para satisfacer los antojos.");
        snacksConsejos.add("Bastones de apio con mantequilla de cacahuete: Proporciona proteínas y fibra. Un snack equilibrado y delicioso.");
        snacksConsejos.add("Batido de proteínas: Hecho con proteína en polvo, leche o agua, y frutas para aumentar el contenido nutricional.");
        snacksConsejos.add("Yogur griego sin grasa con frutas: Alto en proteínas y bajo en grasa. Una opción cremosa y saludable.");
        snacksConsejos.add("Nueces mixtas sin sal: Contienen grasas saludables y proteínas. Un snack portátil y nutritivo.");
        snacksConsejos.add("Huevo duro: Rico en proteínas y fácil de llevar. Un snack saciante.");
        snacksConsejos.add("Hummus con bastones de pimiento: Proporciona proteínas y vitaminas. Un aperitivo delicioso y saludable.");
        snacksConsejos.add("Tiras de pavo o pollo sin piel: Bajas en grasa y altas en proteínas. Un snack magro y sabroso.");
        snacksConsejos.add("Yogur de coco sin azúcar añadido con bayas: Alternativa sin lácteos, con sabor a coco y antioxidantes de las bayas.");
        snacksConsejos.add("Rebanadas de manzana con mantequilla de almendra: Proporciona proteínas y fibra. Un snack equilibrado y energético.");
        snacksConsejos.add("Queso cottage bajo en grasa con piña: Alto en proteínas y bajo en grasa. Una opción dulce y saludable.");
        snacksConsejos.add("Tiras de pimiento con guacamole: Proporcionan vitaminas y grasas saludables. Un snack delicioso y lleno de sabor.");
        snacksConsejos.add("Hojuelas de avena con frutos secos: Proporcionan fibra y grasas saludables. Un snack crujiente y satisfactorio.");
        snacksConsejos.add("Barritas de proteínas: Hechas con proteína en polvo, nueces y frutas. Un snack conveniente para llevar.");
        snacksConsejos.add("Edamame: Son granos de soja inmaduros y ricos en proteínas. Un snack saludable y abundante.");
        snacksConsejos.add("Pepitas de calabaza tostadas: Contienen proteínas y minerales como el zinc y el hierro. Un snack crujiente y nutritivo.");
        snacksConsejos.add("Huevos de codorniz hervidos: Pequeños y ricos en proteínas. Un snack proteico y fácil de preparar.");
        snacksConsejos.add("Tiras de pepino con tzatziki: Proporcionan hidratación y proteínas. Un snack fresco y saludable.");
        snacksConsejos.add("Barritas de granola caseras: Hechas con avena, frutos secos y miel. Un snack lleno de energía y fibra.");
        snacksConsejos.add("Yogur de soja sin azúcar añadido con frutas: Alternativa sin lácteos, rica en proteínas y con sabor a frutas.");
        snacksConsejos.add("Pipas de girasol sin sal: Contienen grasas saludables y proteínas. Un snack fácil de llevar.");
        snacksConsejos.add("Pan integral con aguacate y tomate: Proporciona fibra y grasas saludables. Un snack saciante y delicioso.");

        List<String> fibraConsejos = new ArrayList<>();
        fibraConsejos.add("Ciruelas pasas: Son una excelente fuente de fibra soluble que puede ayudar a mantener la regularidad intestinal.");
        fibraConsejos.add("Avena: Rica en fibra soluble que ayuda a mantener estable el azúcar en sangre. Se utiliza en el desayuno, como avena cocida o en batidos.");
        fibraConsejos.add("Quinua: Contiene proteínas completas y es rica en minerales como el hierro y el magnesio. Se utiliza como guarnición o base para ensaladas.");
        fibraConsejos.add("Arroz integral: Mayor contenido nutricional en comparación con el arroz blanco. Se utiliza como guarnición o en platos como el arroz frito integral.");
        fibraConsejos.add("Lentejas: Fuente de proteínas, fibra y hierro. Se utilizan en sopas, guisos y ensaladas.");
        fibraConsejos.add("Garbanzos: Contienen proteínas, fibra y folato. Se utilizan en platos como el hummus y guisos.");
        fibraConsejos.add("Frijoles negros: Ricos en fibra y proteínas. Se utilizan en platos mexicanos, como los frijoles refritos.");
        fibraConsejos.add("Pistachos: Contienen fibra y grasas saludables. Se consumen como snack o se utilizan en recetas.");
        fibraConsejos.add("Peras: Ricas en fibra soluble y antioxidantes. Se consumen como fruta fresca o en ensaladas.");
        fibraConsejos.add("Ciruelas pasas: Contienen fibra y ayudan a la digestión. Se consumen como snack o se añaden a la avena.");
        fibraConsejos.add("Brócoli: Fuente de fibra y vitaminas. Se consume como guarnición o en ensaladas.");
        fibraConsejos.add("Manzanas: Contienen fibra y antioxidantes. Se consumen como fruta fresca o en compotas.");
        fibraConsejos.add("Frambuesas: Ricas en fibra y antioxidantes. Se consumen como fruta fresca o en batidos.");
        fibraConsejos.add("Pan integral: Contiene más fibra que el pan blanco. Se utiliza para sándwiches y tostadas.");
        fibraConsejos.add("Pera: Rica en fibra y vitaminas. Se consume como fruta fresca o en ensaladas.");
        fibraConsejos.add("Zanahorias: Contienen fibra y betacarotenos. Se consumen como snack o en ensaladas.");
        fibraConsejos.add("Palomitas de maíz (sin mantequilla ni exceso de sal): Son una fuente sorprendente de fibra. Se pueden disfrutar como snack ligero.");
        fibraConsejos.add("Higos frescos: Contienen fibra y son naturalmente dulces. Se consumen como fruta fresca o en postres.");
        fibraConsejos.add("Espinacas: Ricas en hierro, fibra y vitaminas. Se consumen en ensaladas y platos cocidos.");
        fibraConsejos.add("Fresas: Bajas en calorías y ricas en vitamina C. Se consumen como fruta fresca o en batidos.");
        fibraConsejos.add("Kiwi: Rico en fibra y vitamina C. Se consume como fruta fresca o en ensaladas de frutas.");
        fibraConsejos.add("Pan de centeno integral: Contiene fibra y es una alternativa al pan blanco. Se utiliza para sándwiches.");
        fibraConsejos.add("Cerezas: Ricas en fibra y antioxidantes. Se consumen como fruta fresca o en postres.");
        fibraConsejos.add("Habas: Contienen fibra y proteínas. Se utilizan en guisos y ensaladas.");
        fibraConsejos.add("Alcachofas: Ricas en fibra y antioxidantes. Se consumen cocidas o en platos gratinados.");
        fibraConsejos.add("Pasas: Contienen fibra y son una opción de snack natural. Se consumen como snack o se añaden a la avena.");
        fibraConsejos.add("Mango: Rico en fibra y vitamina C. Se consume como fruta fresca o en ensaladas.");
        fibraConsejos.add("Semillas de chía: Contienen fibra y grasas saludables. Se añaden a batidos, yogures y avena.");
        fibraConsejos.add("Ciruelas pasas: Contienen fibra y ayudan a la digestión. Se consumen como snack o se añaden a la avena.");
        fibraConsejos.add("Higos secos: Son naturalmente dulces y ricos en fibra. Se consumen como snack o se añaden a ensaladas.");
        fibraConsejos.add("Granada: Contiene fibra y antioxidantes. Se consume como fruta fresca o en ensaladas.");
        fibraConsejos.add("Pepitas de calabaza: Contienen fibra y minerales como el zinc. Se consumen como snack o se añaden a ensaladas.");
        fibraConsejos.add("Ciruelas pasas: Contienen fibra y ayudan a la digestión. Se consumen como snack o se añaden a la avena.");
        fibraConsejos.add("Arándanos: Ricos en fibra y antioxidantes. Se consumen como fruta fresca o en batidos.");
        fibraConsejos.add("Kiwis: Ricos en fibra y vitamina C. Se consumen como fruta fresca o en ensaladas.");
        fibraConsejos.add("Ciruelas pasas: Contienen fibra y ayudan a la digestión. Se consumen como snack o se añaden a la avena.");
        fibraConsejos.add("Semillas de chía: Contienen fibra y grasas saludables. Se añaden a batidos, yogures y avena.");
        fibraConsejos.add("Alcachofas: Ricas en fibra y antioxidantes. Se consumen cocidas o en platos gratinados.");
        fibraConsejos.add("Pasas: Contienen fibra y son una opción de snack natural. Se consumen como snack o se añaden a la avena.");
        fibraConsejos.add("Mango: Rico en fibra y vitamina C. Se consume como fruta fresca o en ensaladas.");
        fibraConsejos.add("Granada: Contiene fibra y antioxidantes. Se consume como fruta fresca o en ensaladas.");

        List<String> algasConsejos = new ArrayList<>();
        algasConsejos.add("Nori: Hojas de algas secas y oscuras utilizadas para hacer sushi. Ricas en minerales y vitaminas.");
        algasConsejos.add("Wakame: Alga verde utilizada en ensaladas y sopas. Fuente de calcio y yodo.");
        algasConsejos.add("Dulse: Alga roja con sabor ahumado que se come como snack o se agrega a platos. Rica en minerales y antioxidantes.");
        algasConsejos.add("Kombu: Alga marina utilizada para hacer caldos y sopas. Contiene glutamato natural para mejorar el sabor.");
        algasConsejos.add("Hijiki: Alga marrón utilizada en platos japoneses y coreanos. Rica en minerales como el hierro y el calcio.");
        algasConsejos.add("Espaguetis de mar: Alga marrón que se puede usar como sustituto de pasta. Contiene minerales y fibra.");

        // Agrega las listas de consejos a la categoría correspondiente
        consejos.put("Verduras y Hortalizas", verdurasConsejos);
        consejos.put("Frutas", frutasConsejos);
        consejos.put("Granos Integrales", granosConsejos);
        consejos.put("Legumbres", legumbresConsejos);
        consejos.put("Proteínas Magras", proteinasConsejos);
        consejos.put("Fuentes de Grasas Saludables", grasasConsejos);
        consejos.put("Productos lácteos bajos en grasa", lacteosConsejos);
        consejos.put("Especias y Hierbas", especiasConsejos);
        consejos.put("Bebidas Saludables", bebidasConsejos);
        consejos.put("Opciones de Snacks Saludables", snacksConsejos);
        consejos.put("Alimentos Ricos en Fibra", fibraConsejos);
        consejos.put("Algas Marinas", algasConsejos);
        
        
    }

        public String obtenerConsejoAleatorio(String categoria) {
        List<String> consejosCategoria = consejos.get(categoria);
        if (consejosCategoria != null && !consejosCategoria.isEmpty()) {
            Random random = new Random();
            int indiceAleatorio = random.nextInt(consejosCategoria.size());
            return consejosCategoria.get(indiceAleatorio);
        }
        return "No hay consejos disponibles para esta categoría.";
    }
}
